lab5_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls'))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.MatKulCreate.as_view(), name="Mata_Kuliah_Create"),
    path('list/', views.MatKulList.as_view(), name="Mata_Kuliah_List"),
    path('detail/<int:pk>/', views.MatKulDetail.as_view(), name="Mata_Kuliah_Detail"),
    path('delete/<int:pk>/', views.MatKulDelete.as_view(), name="Mata_Kuliah_Delete")
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='home'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='home'),
    path('search/', views.search, name="search")
]

main/models.py
from django.db import models


class MataKuliah(models.Model): # pragma: no cover

    nama = models.CharField(max_length=128)
    dosen = models.CharField(max_length=128)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    semester_tahun = models.CharField(max_length=32)
    ruang_kelas = models.CharField(max_length=8)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

main/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from django import forms
from .models import MataKuliah


class AddMataKuliahForm(forms.ModelForm): # pragma: no cover
    semester = forms.ChoiceField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], label="Semester")
    tahun = forms.ChoiceField(choices=[(f'{tahun}/{tahun + 1}', f'{tahun}/{tahun + 1}') for tahun in range(2000, 2100)],
                              label="Tahun")

    def __init__(self, *args, **kwargs): # pragma: no cover
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'nama', 'dosen', 'jumlah_sks', 'deskripsi', 'ruang_kelas',
            Div(
                Div('semester', css_class='col-md-6', ),
                Div('tahun', css_class='col-md-6', ),
                css_class='row',
            ),
            FormActions(
                Submit('submit', 'Tambahkan', css_class='btn btn-primary btn-lg btn-block'),
            ),
        )

    class Meta:
        model = MataKuliah
        fields = ['nama', 'dosen', 'jumlah_sks', 'deskripsi', 'ruang_kelas', 'semester', 'tahun']

main/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import list, detail, edit

from .forms import AddMataKuliahForm
from .models import MataKuliah


def home(request): # pragma: no cover
    return redirect(reverse("main:Mata_Kuliah_List"))


class MatKulCreate(edit.CreateView): # pragma: no cover
    model = MataKuliah
    # fields = ['nama', 'dosen', 'jumlah_sks', 'deskripsi', 'ruang_kelas', 'semester', 'tahun']
    form_class = AddMataKuliahForm
    success_url = "/list"
    template_name = "main/add.html"

    def form_valid(self, form):
        form.instance.semester_tahun = form.cleaned_data['semester'] + " " + form.cleaned_data['tahun']
        return super(MatKulCreate, self).form_valid(form)


class MatKulList(list.ListView): # pragma: no cover
    model = MataKuliah
    template_name = "main/list.html"


class MatKulDetail(detail.DetailView): # pragma: no cover
    model = MataKuliah
    template_name = "main/detail.html"

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            messages.add_message(request, messages.ERROR,
                                 'Tidak ditemkan mata kuliah dengan id tersebut atau mata kuliah tersebut sudah dihapus')
            return redirect(reverse("main:Mata_Kuliah_List"))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        pk = self.kwargs['pk']
        return super().get_context_data(**kwargs)


class MatKulDelete(edit.DeleteView): # pragma: no cover
    model = MataKuliah
    template_name = "main/delete.html"

    def get_context_data(self, **kwargs):
        pk = self.kwargs['pk']
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        try:
            self.object.delete()
        except Exception:
            messages.add_message(request, messages.ERROR, 'Tidak dapat menghapus objek')
            return HttpResponseRedirect(success_url)

        messages.add_message(request, messages.SUCCESS, 'Berhasil menghapus objek')

        return HttpResponseRedirect(success_url)

    success_url = reverse_lazy("main:Mata_Kuliah_List")

story7/views.py
from django.shortcuts import render


def index(request):
    return render(request, "story7/index.html")

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests


def search(request):
    url = f'https://www.googleapis.com/books/v1/volumes?q={request.GET["q"]}&maxResults=9'

    result = requests.get(url)
    return JsonResponse(result.json(), status=result.status_code)


def index(request):
    return render(request, "story8/index.html")

main/templates/main/add.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
    <title>Tambahkan Mata Kuliah</title>
{% endblock meta %}

{% block content %}
    <div class="row align-items-center">
        <div class=" col-12">
            <div class="card">
                <div class="card-header text-dark">
                    Tambahkan Mata Kuliah
                </div>
                <div class="card-body text-muted">
                    <form method="post">{% csrf_token %}
                        {% crispy form %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/delete.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Hapus Mata Kuliah</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
{% endblock meta %}

{% block content %}
    <form method="post" id="delete-form">{% csrf_token %}
    </form>
{% endblock content %}

{% block customScript %}
    <script type="text/javascript">
        $(function () {
            swal.fire({
                title: 'Konfirmasi Penghapusan?',
                text: "Yakin ingin menghapus mata kuliah: {{ object.nama }}",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Ya!',
                cancelButtonText: 'Tidak!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#delete-form').submit()
                } else {
                    window.location.replace("{% url 'main:Mata_Kuliah_List' %}");
                }
            })
        });
    </script>
{% endblock customScript %}

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Detail Mata Kuliah</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
{% endblock meta %}

{% block content %}
    <div class="row align-items-center">
        <div class=" col-12">
            <div class="card">
                <div class="card-header text-dark">
                    Detail Mata Kuliah: {{ object.nama }}
                </div>
                <div class="card-body">
                    <h4 class="card-title text-dark">{{ object.nama }}</h4>
                    <h6 class="card-subtitle mb-2 text-muted">Dosen: {{ object.dosen }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Kelas: {{ object.ruang_kelas }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Sks: {{ object.jumlah_sks }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Semester/tahun: {{ object.semester_tahun }}</h6>
                    <p class="card-text text-dark">{{ object.deskripsi }}</p>
                    <div class="text-center mt-4">
                        <a href="{% url 'main:Mata_Kuliah_List' %}" class="btn btn-primary mr-4">Kembali ke daftar</a>
                        <a href="{% url 'main:Mata_Kuliah_Delete' pk=object.id %}" class="btn btn-danger">Hapus mata
                            kuliah</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/list.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Daftar Mata Kuliah</title>
{% endblock meta %}

{% block content %}
    <div class="row align-items-center">
        <div class=" col-12">
            <div class="card">
                <div class="card-header text-dark">
                    Daftar Mata Kuliah
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Mata Kuliah</th>
                            <th scope="col">Dosen</th>
                            <th scope="col">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for mataKuliah in object_list %}
                            <tr>
                                <td>{{ mataKuliah.nama }}</td>
                                <td>{{ mataKuliah.dosen }}</td>
                                <td><a class="btn btn-primary"
                                       href="{% url "main:Mata_Kuliah_Detail" pk=mataKuliah.id %}"
                                       role="button">Detail</a></td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3"> No Data Yet</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <a href="{% url 'main:Mata_Kuliah_Create' %}" class="btn btn-primary btn-lg btn-block mt-4">Tambahkan
                        Mata Kuliah</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

story7/templates/story7/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
    <title>Tambahkan Mata Kuliah</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"
          integrity="sha384-xewr6kSkq3dBbEtB6Z/3oFZmknWn7nHqhLVLrYgzEFRbU/DHSxW7K3B44yWUN60D" crossorigin="anonymous">
    <style>
        .head {
            display: flex !important;
            background-color: #333333;
        }

        .head1 {
            display: flex !important;
            justify-content: space-between !important;
            width: 100%;
        }
    </style>
{% endblock meta %}

{% block site_title %}Story 7{% endblock site_title %}
{% block page_title %}
    <a class="text-light" href="{% url 'story7:home' %}">Client Side Scripting</a>{% endblock page_title %}

{% block content %}
    <div class="row align-items-center">
        <div class=" col-12">
            <div class="card">
                <div class="card-header text-dark">
                    Accordion
                </div>
                <div class="card-body text-muted">
                    <div id="accordion">
                        <div class="group">
                            <div class="head">
                                <div class="head1">
                                    <div class="accordion-title"><h3>Aktivitas saat ini</h3></div>
                                    <div class="accordion-btn">
                                        <button type="button" class="btn btn-light up"><i class="fa fa-chevron-up"></i></button>
                                        <button type="button" class="btn btn-light down"><i class="fa fa-chevron-down"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <p>Saat ini sedang mengerjakan story 7 PPW.</p>
                            </div>
                        </div>
                        <div class="group">
                            <div class="head">
                                <div class="head1">
                                    <div class="accordion-title"><h3>Pengalaman berorganisasi</h3></div>
                                    <div class="accordion-btn">
                                        <button type="button" class="btn btn-light up"><i class="fa fa-chevron-up"></i></button>
                                        <button type="button" class="btn btn-light down"><i class="fa fa-chevron-down"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <ul>
                                    <li>RISTEK</li>
                                    <li>Panitia Compfest</li>
                                </ul>
                            </div>
                        </div>
                        <div class="group">
                            <div class="head">
                                <div class="head1">
                                    <div class="accordion-title"><h3>Prestasi</h3></div>
                                    <div class="accordion-btn">
                                        <button type="button" class="btn btn-light up"><i class="fa fa-chevron-up"></i></button>
                                        <button type="button" class="btn btn-light down"><i class="fa fa-chevron-down"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <ul>
                                    <li>Belum ada</li>
                                </ul>
                            </div>
                        </div>
                        <div class="group">
                            <div class="head">
                                <div class="head1">
                                    <div class="accordion-title"><h3>Hobi</h3></div>
                                    <div class="accordion-btn">
                                        <button type="button" class="btn btn-light up"><i class="fa fa-chevron-up"></i></button>
                                        <button type="button" class="btn btn-light down"><i class="fa fa-chevron-down"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <p>Hobi saya adalah ngoding. </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block customScript %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
            integrity="sha384-JPbtLYL10d/Z1crlc6GGGGM3PavCzzoUJ1UxH0bXHOfguWHQ6XAWrIzW+MBGGXe5"
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(function () {
            const up = $('.up');
            const down = $('.down');
            const accordion = $("#accordion");
            const body = $('body');
            const click_handler_up = function (e) {
                e.stopImmediatePropagation();

                const $this = $(this);
                const target = $this.closest('.group');
                const prev = target.prev();

                console.log("up " + $this.text());

                (prev.clone()).insertAfter(target);
                prev.remove();

                body.off("click", '.up');

                //up.on("click", click_handler_up);
                body.on("click", '.up', click_handler_up);

                accordion.accordion('option', {animate: false});
                accordion.accordion("refresh");
                accordion.accordion('option', {active: false, animate: true});

            };
            const click_handler_down = function (e) {
                e.stopImmediatePropagation();

                const $this = $(this);
                const target = $this.closest('.group');
                const next = target.next();

                console.log("down " + $this.text());

                (next.clone()).insertBefore(target);
                next.remove();

                body.off("click", '.down');

                body.on("click", '.down', click_handler_down);

                accordion.accordion('option', {animate: false});
                accordion.accordion("refresh");
                accordion.accordion('option', {active: false, animate: true});

            };
            body.on("click", '.up', click_handler_up);
            body.on("click", '.down', click_handler_down);
            accordion
                .accordion({
                    header: "> div > .head",
                    collapsible: true,
                    active: false
                })
                .sortable({
                    axis: "y",
                    handle: ".head",
                    stop: function (event, ui) {
                        // IE doesn't register the blur when sorting
                        // so trigger focusout handlers to remove .ui-state-focus
                        ui.item.children("h3").triggerHandler("focusout");

                        // Refresh accordion to handle new order
                        $(this).accordion("refresh");
                    }
                });
        });
    </script>
{% endblock customScript %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <script src="https://kit.fontawesome.com/71a893d14e.js" crossorigin="anonymous"></script>

    {% block skip_main_css %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    {% endblock skip_main_css %}

    {% block meta %}
    {% endblock meta %}

</head>

<body class="home-section">
<nav class="navbar navbar-light bg-dark">
    <span class="navbar-brand mb-0 h1" style="color: #fff;">{% block site_title %}Mata
        Kuliah{% endblock site_title %}</span>
    <span class="navbar-text">
        {% block page_title %}<a class="text-light"
                                 href="{% url 'main:Mata_Kuliah_List' %}">Daftar Mata Kuliah</a>{% endblock page_title %}
    </span>
</nav>
<div class="container pt-5 pb-5">
    {% block content %}
    {% endblock content %}
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"
        integrity="sha384-KcyRSlC9FQog/lJsT+QA8AUIFBgnwKM7bxm7/YaX+NTr4D00npYawrX0h+oXI3a2"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.5.1/dist/sweetalert2.all.min.js"
        integrity="sha256-fVZveEm3wEm6RojWh41ywhrs4nbQjta1e9oDyovzI3E=" crossorigin="anonymous"></script>

<script type="text/javascript">
    $(function () {
        const modals = [];
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    modals.push({
                        icon: 'error',
                        title: 'Gagal...',
                        text: "{{ message }}",
                    })
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    modals.push({
                        icon: 'success',
                        title: 'Sukses!',
                        text: "{{ message }}",
                    })
                {% endif %}
            {% endfor %}
        {% endif %}
        swal.queue(modals);
    });
</script>
{% block customScript %}
{% endblock customScript %}
</body>

</html>